# Build and check LDGLite x86 and x86_64 architectures unsing Qt/MinGW platform
version: 'LDGLite-AV-1.3.3.{build}'

clone_folder: c:\projects\ldglite

# skip automatic cloning because we want restore cached items in the clone directory first
clone_script: echo skip

# we're caching qt5 for MinGW x86_64 and the LDraw library
cache:
 - 'C:\projects\$(ldgl_librepo)'
 - '$(APPVEYOR_BUILD_FOLDER)\LDraw'

shallow_clone: true

branches:
  only:
   - master

configuration: release

matrix:
  fast_finish: true

environment:
  LDGL_DIST_DIR: lpub3d_windows_3rdparty
  LDGL_DIST_DIR_PATH: $(APPVEYOR_BUILD_FOLDER)\$(LDGL_DIST_DIR)
  QT32_BASE: C:\Qt\5.9.2\mingw53_32\bin
  QT32_UTILS: C:\Qt\Tools\mingw530_32\bin
  QT64_BASE: C:\msys64\MINGW64\bin
  ldgl_qtlibs: mingw-w64-x86_64-qt5-5.9.1-1-any.pkg.tar.xz
  ldgl_iculibs: mingw-w64-x86_64-icu-58.2-2-any.pkg.tar.xz
  ldgl_librepo: lpub3d_mingw-x86_64_libs
  ldgl_librepodir: /c/projects/$(ldgl_librepo)
  ldgl_msys2env: /c/msys64/usr/bin

init:
 - ps: write-host "Building LDGLite x86 and x86_64 architectures..."
 - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
 - ps: |
      If ($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains("[build pkg]")) {
        write-host "[build pkg] detected."
        $env:LDGL_BUILD_PKG = "yes"
      }
 - ps: |
      If ($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains("[deploy pkg]")) {
        write-host "[deploy pkg] detected."
        $env:LDGL_BUILD_PKG = "yes"
        $env:LDGL_DEPLOY_PKG = $true
      }
 - ps: Get-ChildItem Env:ldgl_* | Sort-Object name

# This is where we install Qt5 for x86_64 builds along with ICU v58. The source for these items are cached but if not then they are
# downloded. After setting up these items, we proceed to fetch the commit that triggered the AppVeyor build.
# We don't use git clone because the 'clone_directory' is not empty (restored cached components were added in previous steps) - so the
# git clone command will fail. Instead we use fetch and checkout to pretty much replicate the same behaviour as the default git clone.
# This includes setting the clone depth, and fetching the last commit and previous tags
install:
 - cmd: git init %APPVEYOR_BUILD_FOLDER%
 - cmd: cd %APPVEYOR_BUILD_FOLDER%
 - cmd: git remote add origin https://github.com/%APPVEYOR_REPO_NAME%.git
 - cmd: git fetch -qfup --depth=200 origin +%APPVEYOR_REPO_BRANCH% +refs/tags/*:refs/tags/*
 - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%
 - cmd: bash -lc "if ! test -d ${ldgl_librepodir}; then curl -sL -o ${ldgl_librepo}.tar.gz https://github.com/trevorsandy/${ldgl_librepo}/archive/master.tar.gz; fi"
 - cmd: bash -lc "if ! test -d ${ldgl_librepodir}; then mkdir -p ${ldgl_librepodir} && tar -xzf ${ldgl_librepo}.tar.gz -C ${ldgl_librepodir} --strip-components=1; fi"
 - cmd: bash -lc "if ! test -d ${ldgl_librepodir}; then echo repository ${ldgl_librepodir} not found; else echo library repository available at ${ldgl_librepodir}; fi"
 - cmd: bash -lc "export PATH=${ldgl_msys2env}:$PATH; cd ${ldgl_librepodir}/qt-5.9.1-1-release; pacman -U --needed --noconfirm ${ldgl_qtlibs} ${ldgl_iculibs}"

build_script:
 - ps: |
      write-host "  Distribution directory..[$env:LDGL_DIST_DIR_PATH]"
      write-host "  Working Directory.......[$PWD]"
      If ($env:LDGL_BUILD_PKG -eq "yes") {
        cmd.exe /c "build.cmd -all -ins -chk"
        $env:LDGL_ARTEFACT_ITEM_COUNT = (Get-ChildItem -Path $env:LDGL_DIST_DIR_PATH -Recurse).count
        write-host "`n  Artifact count....[$env:LDGL_ARTEFACT_ITEM_COUNT]"
      } Else {
        cmd.exe /c "build.cmd -all -chk -minlog"
      }

test: off

after_build:
 - ps: |
      If (($env:LDGL_BUILD_PKG -eq "yes") -and ([int]$env:LDGL_ARTEFACT_ITEM_COUNT -gt 5)){
        cd $env:APPVEYOR_BUILD_FOLDER; write-host "Creating zip archive artefact from ./$env:LDGL_DIST_DIR..."
        7z a -tzip $env:LDGL_DIST_DIR $env:LDGL_DIST_DIR | Select-String -Pattern '(^Creating)|(^Everything)' -CaseSensitive; write-host "Zip archive $env:LDGL_DIST_DIR.zip created."
        $root = Resolve-Path $env:APPVEYOR_BUILD_FOLDER; [IO.Directory]::GetFiles($root.Path, '*.zip', 'TopDirectoryOnly') | % { Push-AppveyorArtifact $_ -Type zip -FileName $_.Substring($root.Path.Length + 1) -DeploymentName $env:LDGL_DIST_DIR}
      }

deploy:
 - provider: GitHub
   repository: trevorsandy/ldglite
   description: 'LDGLite - Windows archive package of LPub3D image renderer'
   auth_token:
     secure: rnf4qpF81ISjm8q13OgkAaoKZReXpjODhU9fbGFMhMydHrda1ezLubGXRU9OKGu4
   release: $(LDGL_DIST_DIR)
   artifact: $(LDGL_DIST_DIR).zip
   prerelease: true
   force_update: true
   on:
    branch: master
    ldgl_deploy_pkg: true
